language: python

python:
  - '3.6'

service:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - export APP_SETTINGS=project.config.TestingConfig

script:
  - python manage.py test
